blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://wreathe.dev
    about: Report documentation issues on the doc-repository. 

  - name: Support Question
    url: https://wreathe.dev
    about: Post your question on the discussion board instead of our issue tracker.

  - name: Discord Chat
    url: https://discord.gg/kRhHHjQR
    about: Join our Discord chat, if you need additional help.
